name: Update JSON URL

on:
  workflow_dispatch:
    inputs:
      new_value_e:
        description: 'Select value for "enabled"'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false
      new_value_l:
        description: 'New URL string value'
        required: true
        default: ''

jobs:
  update-json:
    runs-on: ubuntu-latest

    concurrency:
      group: update-json
      cancel-in-progress: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Run custom action script
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
      run: |
        node .github/scripts/update-json.js "${{ github.event.inputs.new_value_e }}" "${{ github.event.inputs.new_value_l }}" "$ENCRYPTION_KEY" "$ENCRYPTION_IV"

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Update JSON from GitHub Actions'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
